[serial]
port = "/dev/ttyUSB0"
baud = 9600

[[slider]]
id = 0
targets = ["system"]

[[slider]]
id = 1
targets = ["vivaldi"]

[[slider]]
id = 2
targets = ["java"]

[[slider]]
id = 3
targets = ["Discord"]

[[slider]]
id = 4
targets = ["spotify", "vlc"]