[serial]
port = "/dev/ttyUSB0"
baud = 9600

[[slider]]
id = 0
target = "system"

[[slider]]
id = 1
target = "vivaldi"

[[slider]]
id = 2
target = "java"

[[slider]]
id = 3
target = "Discord"

[[slider]]
id = 4
target = "spotify"